"""empty message

Revision ID: 776f44b8d35e
Revises: db1e28ca5b98
Create Date: 2016-05-08 23:59:15.603000

"""

# revision identifiers, used by Alembic.
revision = '776f44b8d35e'
down_revision = 'db1e28ca5b98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
