"""empty message

Revision ID: f6c773985d2d
Revises: 72bd908eb38a
Create Date: 2016-05-01 23:43:24.371000

"""

# revision identifiers, used by Alembic.
revision = 'f6c773985d2d'
down_revision = '72bd908eb38a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
